// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Income struct {
	IncomeID  int64
	Name      string
	Money     int64
	Timestamp time.Time
}
