// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getIncome = `-- name: GetIncome :one
SELECT income_id, name, money, timestamp FROM income
WHERE income_id  = ? LIMIT 1
`

func (q *Queries) GetIncome(ctx context.Context, incomeID int64) (Income, error) {
	row := q.db.QueryRowContext(ctx, getIncome, incomeID)
	var i Income
	err := row.Scan(
		&i.IncomeID,
		&i.Name,
		&i.Money,
		&i.Timestamp,
	)
	return i, err
}

const insertIncome = `-- name: InsertIncome :execresult
insert into income (
        name, 
        money,
        timestamp
)values (?, ?, ?)
`

type InsertIncomeParams struct {
	Name      string
	Money     int64
	Timestamp time.Time
}

func (q *Queries) InsertIncome(ctx context.Context, arg InsertIncomeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertIncome, arg.Name, arg.Money, arg.Timestamp)
}
