// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const allIncomes = `-- name: AllIncomes :many
select income_id, name, money, timestamp from income
`

func (q *Queries) AllIncomes(ctx context.Context) ([]Income, error) {
	rows, err := q.db.QueryContext(ctx, allIncomes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.IncomeID,
			&i.Name,
			&i.Money,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncome = `-- name: GetIncome :one
SELECT income_id, name, money, timestamp FROM income
WHERE income_id  = ? LIMIT 1
`

func (q *Queries) GetIncome(ctx context.Context, incomeID int64) (Income, error) {
	row := q.db.QueryRowContext(ctx, getIncome, incomeID)
	var i Income
	err := row.Scan(
		&i.IncomeID,
		&i.Name,
		&i.Money,
		&i.Timestamp,
	)
	return i, err
}

const insertIncome = `-- name: InsertIncome :execresult
insert into income (
        name, 
        money,
        timestamp
)values (?, ?, ?)
`

type InsertIncomeParams struct {
	Name      string
	Money     int64
	Timestamp time.Time
}

func (q *Queries) InsertIncome(ctx context.Context, arg InsertIncomeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertIncome, arg.Name, arg.Money, arg.Timestamp)
}
